name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  test:
    name: ci-build
    runs-on: ubuntu-latest
    services:
      databend:
        image: datafuselabs/databend-query
        env:
          EMBEDDED_DIR: "/.databend/meta"
          HTTP_HANDLER_HOST: "0.0.0.0"
          HTTP_HANDLER_PORT: "8000"
        # options: >-
        #   --health-cmd "curl -fs http://localhost:8000/v1/health || exit 1"
        #   --health-interval 10s
        #   --health-timeout 5s
        #   --health-retries 5
        ports:
          - 8000:8000
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.18"
      - name: Verify Service Running
        run: |
          docker ps -a
          curl -v http://localhost:8000/v1/health
      - name: Test
        env:
          TEST_DATABEND_DSN: "http://databend:databend@localhost:8000/books?idle_timeout=1h"
        run: |
          make test
