name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  test:
    runs-on: ubuntu-latest
    services:
      databend:
        # image: datafuselabs/databend-query
        image: datafuselabs/databend
        env:
          DATABEND_DEFAULT_USER: databend
          DATABEND_DEFAULT_PASSWORD: databend
        # options: >-
        #   --health-cmd "curl -fs http://localhost:8000/v1/health || exit 1"
        #   --health-interval 10s
        #   --health-timeout 5s
        #   --health-retries 5
        ports:
          - 8000:8000
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.18"
      - name: Verify Service Running
        run: |
          cid=$(docker ps -a | grep databend | cut -d' ' -f1)
          docker logs ${cid}
          curl -v http://localhost:8000/v1/health
      - name: Test
        env:
          TEST_DATABEND_DSN: "http://databend:databend@localhost:8000/default?idle_timeout=1h&presigned_url_disabled=1"
        run: |
          make test
          make ci
