name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  test:
    name: ci-build
    runs-on: ubuntu-latest
    container: ubuntu
    services:
      databend:
        image: datafuselabs/databend-query
        ports:
          - 8000:8000
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.18"
      - name: Test
        env:
          TEST_DATABEND_DSN: "http://databend:databend@databend:8000/books?idle_timeout=1h"
        run: |
          make test
